### ISSUE TITLE
ERROR: CCurlFile::FillBuffer - Failed: SSL connect error(35)

### ISSUE THREAD

**Issue by lpuglia** [maxbambi/plugin.video.raitv#10]
**Per utenti raspbian/debian**, l'errore:
```
ERROR: CCurlFile::FillBuffer - Failed: SSL connect error(35)
```
e' dovuto ad un aggiornamento di `openssl` che non permette la connessione sicura (https) a risorse che non hanno una chiave di almeno una certa taglia. per confermare il problema:
```
> curl https://mediapolis.rai.it/
curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
```
per risolverlo e' necessario rimuovere dal file:
```
/etc/ssl/openssl.cnf
```
la linea:
```
CipherString = DEFAULT@SECLEVEL=2
```

**Comment by nx-99** [comment]
curl --version ?

**Comment by lpuglia** [comment]
per dirla tutta e' un problema della versione di ssl (>=1.1.1):

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907788
