### ISSUE TITLE
Errore Rai Play

### ISSUE THREAD

**Issue by sim1pan0** [maxbambi/plugin.video.raitv#11]
Quando provo ad entrare esce : "errore Rai Play visualizza il log per ulteriori informazioni". Ho provato sul PC e funziona mentre sul TV box e sullo smartphone no. Sapete come posso risolvere?

**Comment by maxbambi** [comment]
> Quando provo ad entrare esce : "errore Rai Play visualizza il log per ulteriori informazioni". Ho provato sul PC e funziona mentre sul TV box e sullo smartphone no. Sapete come posso risolvere?

Ce la fai a visualizzare il log ed inviarlo?

**Comment by sim1pan0** [comment]
Ok ora funziona. Grazie
