### ISSUE TITLE
Errore in apertura v. 3.3.8

### ISSUE THREAD

**Issue by myjapan** [maxbambi/plugin.video.raitv#13]
Il plugin non funziona più, dà errore in apertura.
Ho installato la v. 3.3.8 - la v. 3.3.9 installata da zip file mi dà errore di installazione

L'errore loggato quanto provo ad aprire il plugin è il seguente:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
      - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
     Error Type: <type 'exceptions.IndexError'>
     Error Contents: list index out of range
     Traceback (most recent call last):
       File "/home/osmc/.kodi/addons/plugin.video.raitv/default.py", line 46, in <module>
         raisport_keys = cache.cacheFunction(RaiPlay().fillRaiSportKeys)
       File "/home/osmc/.kodi/addons/plugin.video.raitv/resources/lib/StorageServer.py", line 577, in cacheFunction
         ret_val = funct(*args)
       File "/home/osmc/.kodi/addons/plugin.video.raitv/resources/lib/raiplay.py", line 105, in fillRaiSportKeys
         title=dataTematica[0].split('|')[0]
     IndexError: list index out of range
     -->End of Python script error report<--
```

Per ripristinare il funzionamento ho commentato le linee 46 e 558-560 in .kodi/addons/plugin.video.raitv/default.py

**Comment by maxbambi** [comment]
@myjapan, l'errore in quel punto è proprio corretto con la versione 3.3.9...
Se  non riesci ad installarla, puoi guardare l'ultima commit e cambiare il codice direttamente:
è solo un'aggiunta di un try except per gestire chiavi irregolari...
