### ISSUE TITLE
Bug parsing json del palinsesto

### ISSUE THREAD

**Issue by fsp22** [maxbambi/plugin.video.raitv#14]
Ho notato che in alcuni casi la retrieve del palinsesto nel metodo seguente fallisce perché la chiave nel json restituito dalla richiesta non è il nome del canale bensì una stringa vuota.
Ho riscontrato il problema con il palinsesto di R2 nei giorni 11,12 e 13 appena trascorsi.

https://github.com/maxbambi/plugin.video.raitv/blob/c6652c07f5e1b131185b830c7066888c8e51a095/resources/lib/raiplay.py#L191

Un'istruzione di questo tipo risolve il problema

```
key = channelName if channelName in response else ''
oRetVal = response[key][0]["palinsesto"][0]["programmi"]
```

**Comment by maxbambi** [comment]
@fsp22, effettivamente è vero: la struttura rimane la stessa, ma in un caso c'è la chiave con il nome del canale, nell'altro caso solo una stringa vuota...
A dirla tutta, per quella parte lì stiamo ancora utilizzando una url (https://www.raiplay.it/palinsesto/app/old/) che non fa ben sperare per il futuro (visto l'old presente)
In caso di fallimento della versione json, c'è già una funzione che fa il parsing dell'html della pagina del sito con la guida tv...
inserisco subito la modifica...
Tra l'altro sto cercando di mettere a posto il plugin per inserirlo nel repo di kodi ufficiale, ma ho ancora dei grossi problemi con la libreria script.common.plugin.cache che non funziona con python 3, mentre questa compatibilità va assicurata per entrare nel repo.
Se tu volessi collaborare, c'è un branch apposta per la sperimentazione con python3 in kodi 19

**Comment by fsp22** [comment]
mi piacerebbe collaborare,
      ma in questo periodo riesco a ritagliarmi poco tempo. Tuttavia
      seguo il progetto e cerco di dare una mano quando posso
    
    Il 16/11/19 20:36, Max ha scritto:
    
    
      
      @fsp22,
        effettivamente è vero: la struttura rimane la stessa, ma in un
        caso c'è la chiave con il nome del canale, nell'altro caso solo
        una stringa vuota...
        A dirla tutta, per quella parte lì stiamo ancora utilizzando una
        url (https://www.raiplay.it/palinsesto/app/old/)
        che non fa ben sperare per il futuro (visto l'old presente)
        In caso di fallimento della versione json, c'è già una funzione
        che fa il parsing dell'html della pagina del sito con la guida
        tv...
        inserisco subito la modifica...
        Tra l'altro sto cercando di mettere a posto il plugin per
        inserirlo nel repo di kodi ufficiale, ma ho ancora dei grossi
        problemi con la libreria script.common.plugin.cache che non
        funziona con python 3, mentre questa compatibilità va assicurata
        per entrare nel repo.
        Se tu volessi collaborare, c'è un branch apposta per la
        sperimentazione con python3 in kodi 19
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/maxbambi/plugin.video.raitv/issues/14?email_source=notifications\u0026email_token=ADHSC5W5WOQAWB3C4AXGEBTQUBDSJA5CNFSM4JOGDRW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEHY3RQ#issuecomment-554667462",
"url": "https://github.com/maxbambi/plugin.video.raitv/issues/14?email_source=notifications\u0026email_token=ADHSC5W5WOQAWB3C4AXGEBTQUBDSJA5CNFSM4JOGDRW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEHY3RQ#issuecomment-554667462",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
