### ISSUE TITLE
Titolo dei programmi in diretta

### ISSUE THREAD

**Issue by nx-99** [maxbambi/plugin.video.raitv#16]
Molte volte per sapere il titolo del programma che sto guardando faccio riferimento alla sezione replay ed in base al giorno e ora lo trovo.
Sarebbe fattibile sostituirlo in automatico, cioè in base all'orario e canale prendi il titolo da replay?

**Comment by maxbambi** [comment]
@nx-99, 
l'elenco dei canali e dei link alle dirette è accessibile in formato JSON da https://www.raiplay.it/dirette.json: lì non ci sono informazioni sul programma attualmente in onda,
ma ci sono gli importantissimi link agli stream.
Andando a vedere da dove prende le informazioni la pagina web, ho visto che essa legge https://www.raiplay.it/palinsesto/onAir.json che contiene per ogni canale proprio le informazioni del 'currentItem' e del 'nexItem'.
Quindi la risposta è sì e per fare questo basta leggere questo json e aggiungere le informazioni. La controindicazione è che attualmente il plugin crea una copia del menu nella cache per non dover sempre scaricare informazioni dal web e velocizzare la navigazione. Data la necessità di aggiornare il programma attuale (per non mantenere quello di un'ora prima), bisognerebbe disattivare la cache per l'elenco canali (in prima approssimazione non mi sembra un gran rallentamento se ci si riferisce a 15 voci)

**Comment by maxbambi** [comment]
@nx-99,
prova la nuova versione nel branch comp-python3, con le ultime novità da collaudare per inviare tutto nel repo kodi official

**Comment by nx-99** [comment]
@maxbambi 
Bravo, proprio così dicevo.
Vorrei segnalare un piccolo difetto, nella sezione replay di Rai Scuola (anche se inutile perché non disponibili), alcuni titoli non sono allineati, sembra vadano a capo.
![Screenshot_20191206_093908](https://user-images.githubusercontent.com/8221630/70309977-f529fd80-180e-11ea-89fd-e757a93eb33d.png)
Credo che nel plugin originale non accadesse.
Consiglio di inserire il link di Github del addon nel file addon.xml.

**Comment by maxbambi** [comment]
E' dovuto soltanto alla presenza nella stringa del codice della nuova riga...
```
"name": "Memex\nGalileo - episodio 4\nReplica"
``` 
Per risolvere, possiamo fare un replace("\n"," ")

**Comment by nx-99** [comment]
Intendevo in description così da vederlo su kodi
![Screenshot_20191207_110454](https://user-images.githubusercontent.com/8221630/70372598-7e116980-18e1-11ea-9ac3-ff104f168fbf.png)
il replace("\n"," ") funziona, grazie.
