### ISSUE TITLE
Problemi con App Kore e  comp-python3 default.py COLOR yellow

### ISSUE THREAD

**Issue by nx-99** [maxbambi/plugin.video.raitv#19]
Credo che l'applicazione kore di android non digerisca la riga 199 del file default.py :
chName = "[COLOR yellow]" + chName + "[/COLOR]: " + curren
dallo screeshot si vede:
![Screenshot_20191209-112131](https://user-images.githubusercontent.com/8221630/70428497-fc534480-1a76-11ea-933f-877f115b9538.png)
Ho provato a modificarlo così:
chName = chName + ': ' + current + ' '
Sembra andare meglio:
![Screenshot_20191209-113117](https://user-images.githubusercontent.com/8221630/70428789-90bda700-1a77-11ea-8445-0865616422a6.png)
Forse per il colore ci vuole il codice, ma non saprei.

**Comment by maxbambi** [comment]
@nx-99, se vai a vedere il github di kore (https://github.com/xbmc/Kore) ci sono già diverse issue aperte per questo motivo, ad esempio: https://github.com/xbmc/Kore/pull/688
Inizialmente kore non riconosceva neppure [B] o [I], adesso non so...
Controlla quale versione hai installato per vedere se è incluso il merge indicato...

**Comment by nx-99** [comment]
Ok, ho la Versione v2.4.7 Aggiornata 7 giugno 2019, dunque è un problema di Kore non dell'addon.
Aspetterò che aggiornino kore.
