### ISSUE TITLE
Risoluzione video on demand massima è 1024x576

### ISSUE THREAD

**Issue by arthemis841** [maxbambi/plugin.video.raitv#22]
Con l'user-agent settato in relinker.py come "Android 4.2.2 (smart) / RaiPlay 2.1.3 / WiFi"
i film, serie etc on demand possono essere visti massimo a 1024x576, mentre sono disponibili anche a 1280x720.
Se come user-agent (sempre in relinker.py) imposto quello commentato "Chrome 64 on Windows 10", allora riesco a vedere l'on demand a 720p.

**Comment by maxbambi** [comment]
@arthemis841 Aggiornato user-agent nella version 3.4.8

**Comment by mauromol** [comment]
Ciao, io ho correntemente installato la versione 3.4.8, eppure ho constatato anche io che i video vengono sempre riprodotti a 1024x576, nonostante sull'app ufficiale siano disponibili anche a 720p. Qualche idea?

**Comment by maxbambi** [comment]
@mauromol, ti consiglio di installare manualmente l'ultima versione presente qui (3.5.0).

**Comment by mauromol** [comment]
Con la 3.5.0.1 ieri sera in effetti il video che ho visto è partito in 720p, grazie, nonostante sopra tu avessi indicato che la modifica era già stata fatta per la 3.4.8. Quindi personalmente non so spiegarmelo.
Piccola nota a margine, suggerisco di aggiornare il file CHANGELOG :+1:

**Comment by maxbambi** [comment]
@mauromol Per adesso chiudo l'issue.
