### ISSUE TITLE
Errore installazione su Matrix

### ISSUE THREAD

**Issue by MarcoViti** [maxbambi/plugin.video.raitv#24]
Ho provato ad installare l'add-on su Windows 10 64b Pro ma ottengo questo messaggio:
"ERROR <general>: CAddonInstallJob[plugin.video.raitv]: La dipendenza da xbmc.python versione 2.25.0 potrebbe non essere soddisfatta."

Marco.

**Comment by Gythion** [comment]
Devi installare Python 2.25.0

**Comment by MarcoViti** [comment]
Grazie Gythion per la risposta, ho provato a cercare su google, ma trovo riferimenti a vecchie notizie e a versioni precedenti di Kodi.. non sono molto ferrato, mi puoi aiutare?

**Comment by Gythion** [comment]
Ancora l'addon non dovrebbe essere funzionante per Kodi 19, usa 18.7.

**Comment by maxbambi** [comment]
@Gythion @MarcoViti 
In realtà, per poter inserire il plugin nella repository ufficiale di Kodi, sono già stati effettuati dei controlli anche con kodi 19 alpha 1 (installata in Win10 per non interferire con la mia installazione in Ubuntu di Kodi 18.8). 
E' passato molto tempo e quindi forse sono intervenuti dei cambiamenti. Magari do un'occhiata nell'altro pc dove ho il dual boot con Windows 10.

**Comment by MarcoViti** [comment]
@maxbambi 
Grazie per la risposta e l'interessamento,  sono riuscito ad installare l'add-on su windows 10 64b pro Kodi Matrix 19.1 alpha, togliendo la linea "<import addon="xbmc.python" version="2.25.0"/>" dal file addon.xml e l'add-on funziona ... ma solo per i canali dal vivo e le trasmissioni settimanali, se provo a visualizzare dei file dall'archivio mi da errore... probabilmente è cambiato qualcosa sul sito Raiplay..

**Comment by maxbambi** [comment]
@Gythion @MarcoViti 
Sto effettuando adesso la prova con Kodi 19 Matrix alpha1 su win10...
la prima modifica da fare è proprio quella in addon.xml
```
<import addon="xbmc.python" version="3.0.0"/>
```

Gli stream m3u8 funzionano, ci sono invece dei problemi con quelli dash (che ultimamente stanno aumentando di numero)

**Comment by MarcoViti** [comment]
Ciao Max, ho scaricato la nuova versione dell'add-on (3.5.0.1) ma non funziona, a parte che, probabilmente, hai dimenticato di aggiornare il file addon.xml, come avevi detto anche tu nel post precedente a questo, ma anche modificando la riga del codice di  versione  del python inserendo 
<import addon="xbmc.python" version="3.0.0"/>
l'add-on non si installa... appare il messaggio che comunica che l'add-on non è stato installato perchè non rispetta la struttura...

**Comment by gcalzo** [comment]
Anche sulla build ufficiale 19.0 appena rilasciata non si abilita.
Sul mio TIMbox ha fatto l'upgrade da v18.9 a v19.0

**Comment by Gythion** [comment]
Io l'ho scaricato da qui, dalla tendina "Master-Matrix"  e va bene.

**Comment by maxbambi** [comment]
@gcalzo @Gythion @MarcoViti 

Ho creato questo nuovo branch chiamato "matrix" per lavorare sulla versione per kodi 19...
Dai miei test ci sono dei problemi con gli stream dash; il resto sembra funzionare.
Se riesco a trovare il codice giusto da inserire, cerco di correggere anche questo problema e pubblico il plugin su kodi ufficiale
Devo correggere questo (lo pubblico così qualcuno forse mi può aiutare)
```
if "dash" in ct :
        item.setProperty('inputstreamaddon', 'inputstream.adaptive')
        item.setProperty('inputstream.adaptive.manifest_type', 'mpd')
        item.setMimeType('application/dash+xml')
        if key:
            item.setProperty("inputstream.adaptive.license_type", 'com.widevine.alpha')
            item.setProperty("inputstream.adaptive.license_key",  key + '||R{SSM}|')
```

**Comment by maxbambi** [comment]
@Gythion @gcalzo @MarcoViti 
è bastato cambiare 'inputstreamaddon' in 'inputstream' e adesso funziona!

**Comment by sacaiobe** [comment]
Scusa, a me continua a dare dei problemi. Kodi 19 matrix..

**Comment by maxbambi** [comment]
@sacaiobe 
che tipo di problemi?

**Comment by sacaiobe** [comment]
Dice che non va per problemi di strutture .
Mi ribadisci per favore la stringa Kodi? 
Https://github/.... scelta Matrix.zip

Grazie 🙏 



Inviato da Libero Mail per iOS


mercoledì 24 febbraio 2021, 20:15 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by maxbambi** [comment]
@sacaiobe 
ho modificato il file addon.xml ripulendolo da alcune tabulazioni (adesso ci sono solo spazi per le indentazioni)...
ho provato a installarlo nel mio kodi e sembra funzionare...

Riprova... il link per scaricare il file zip direttamente è 
https://github.com/maxbambi/plugin.video.raitv/archive/matrix.zip

**Comment by gcalzo** [comment]
> @sacaiobe
> ho modificato il file addon.xml ripulendolo da alcune tabulazioni (adesso ci sono solo spazi per le indentazioni)...
> ho provato a installarlo nel mio kodi e sembra funzionare...

Brevemente testato ieri sera (uso il plugin al 99,99% per dei "replay" occasionali) e ha funzionato perfettamente! Forse è anche più _reattivo_ di quello per Kodi v18!

**Comment by maxbambi** [comment]
@gcalzo @sacaiobe 
Se tutto funziona, proverò a fare la richiesta di inserimento nel repo ufficiale, così come avvenuto per la versione precedente

**Comment by MarcoViti** [comment]
Con fermo, l'add-on adesso funziona perfettamente

**Comment by maxbambi** [comment]
Ho inviato la pull request sul repo ufficiale di Kodi... 
speriamo che sia accettata nel minor tempo possibile

**Comment by maxbambi** [comment]
@Gythion @gcalzo @MarcoViti @sacaiobe 
Il plugin è stato inserito nel repository ufficiale di Kodi 19!

Quello che non capisco è perché, quando tento di installarlo da repository, mi si blocca tutto e dopo qualche istante Kodi va in crash...

Ho notato che mi succede la stessa cosa quanto tento di installare gli addon che hanno altre dipendenze (forse è inputstreamhelper che crea problemi?), mentre quelli senza dipendenze si installano subito...

Senza problemi l'installazione dallo zip... mah!
Ditemi se anche voi avete questi problemi...

**Comment by gcalzo** [comment]
A me va in crash (versione ds zip!) aprendolo da addon/i miei addon e selezionando "requisiti"! Temo proprio che ci sia un problema con le dipendenze...
Al momento io nella repo ufficiale ancora non lo vedo...

**Comment by MarcoViti** [comment]
Salve ragazzi, a me si installa tranquillamente, sia da repository di Kodi sia da file .zip. (versione add-on 3.6.0)
Ho installata la versione finale di Kodi  Matrix (Starting Kodi (19.0 (19.0.0) Git:20210218-f44fdfbf67). Platform: Windows NT x86 64-bit).

**Comment by maxbambi** [comment]
@MarcoViti ci sono delle cose strane che succedono (ma non sembrano dipendere dall'addon)

Io ho kodi installato sia in Ubuntu che in Win10 (la versione win è la stessa che @MarcoViti ha indicato)
Mi sembra gli riscontrare gli stessi problemi di installazione, ma cosa curiosa, se installo tramite zip una versione più vecchia del plugin, mi effettua correttamente l'aggiornamento alla 3.6.0 

Quindi se direttamente clicco installa mi va in crash, con l'installazione da zip e l'aggiornamento da repository no...

**Comment by MarcoViti** [comment]
Io invece trovo problemi ad istallare il plugin Phate89 (MediasetPlay) ... sia da repository di Kodi, sia da file .zip.. Kody va in crash e si chiude.

**Comment by maxbambi** [comment]
@MarcoViti 
Con MediasetPlay c'è qualche problema... io sono riuscito ad installarlo manualmente copiando il contenuto del file zip all'interno della cartella addon, dopo aver installato tramite zip la libreria phate89 versione 1.2.1

**Comment by maxbambi** [comment]
@gcalzo @Gythion @MarcoViti @sacaiobe 
ho scoperto che il crash avviene se Kodi è impostato in italiano, mentre sembra funzionare correttamente in inglese...
confermatemi se questa cosa succede anche a voi...

**Comment by MarcoViti** [comment]
Si.. confermo. Se la lingua impostata è Italiano va in crash... con la lingua impostata Inglese (usa) gli add-on si installano regolarmente

**Comment by maxbambi** [comment]
HO TROVATO QUELLO CHE NON FUNZIONAVA! 
Il traduttore in italiano ha commesso degli errori di sintassi nelle stringhe che contengono `{0:s}` `{1:s}` eccetera:
le ha scritte come `{0: s}` `{1: s}`, aggiungendo uno spazio

Questo è il file corretto (va tolta l'estensione txt, che ho aggiunto solo perché con estensione po non me lo faceva allegare)
che deve sostituire il file `strings.po` presente nella cartella `addons/resource.language.it_it/resources`
[strings.po.txt](https://github.com/maxbambi/plugin.video.raitv/files/6056626/strings.po.txt)

**Comment by MarcoViti** [comment]
Ciao Max.
Credo sia il caso di fare presente la tua scoperta allo staff di Kodi in modo che aggiornino e inseriscano la tua modifica al programma di istallazione..

**Comment by maxbambi** [comment]
@MarcoViti ho aperto un thread nel forum e ho fatto le correzioni su transifex... speriamo qualcuno lo veda!
