### ISSUE TITLE
Are you planning to port this?

### ISSUE THREAD

**Issue by Razzeee** [maxbambi/plugin.video.raitv#27]
Hey there,

as the next kodi version will only support python 3 addons, this will need a touchup and needs to be resend to the repo. Is that something you would consider doing?

**Comment by maxbambi** [comment]
@Razzeee Yes, of course 
I don't know if there are new issues, but this plugin has been already tested with Kodi 19 Alpha 1 some months ago.

**Comment by Razzeee** [comment]
Ah, sorry, I just would have thought, that you might have send it to the kodi repo then :)
