### ISSUE TITLE
Contenuti bloccati

### ISSUE THREAD

**Issue by power1977** [maxbambi/plugin.video.raitv#28]
Innanzitutto grazie per lo sviluppo di questo plugin e per il tempo che gli hai dedicato.

Vorrei segnalarti una modifica che si potrebbe apportare.

Recentemente per accedere ad alcuni contenuti è necessario avere un account.
Questo plugin non ha parametri configurabili; è possibile inserire questa funzione per sbloccare i contenuti protetti?
Ho avuto problemi con la fiction "un posto al sole".

Grazie

**Comment by arthemis841** [comment]
@maxbambi Ciao, ho notato anche io questo problema. 
Non so se dipenda dal login ma quando ho provato a vedere la replica di Good Doctor il playback non partiva.

**Comment by maxbambi** [comment]
@power1977 @arthemis841 
Per quanto riguarda Good Doctor, ho fatto una correzione stamani (versione 3.4.8) e sono riuscito ad avviarlo
Con la stessa modifica dovrebbe funzionare anche Un posto al sole (perché è lo stesso formato di stream)
