### ISSUE TITLE
Alcuni video non possono essere riprodotti

### ISSUE THREAD

**Issue by lucafabbri365** [maxbambi/plugin.video.raitv#29]
Buonasera,

alcuni video non vengono riprodotti dal plug-in. Ho notato, accedendo al sito RayPlay tramite browser, che gli stessi per essere visualizzati necessitano di autenticazione (Google Account, e/o Facebook, ecc) pertanto. Che sia questo il motivo ? Vi sarebbe la possibilità di aggiungere il supporto per autenticazione nel plug-in ?

Grazie,
Luca

**Comment by maxbambi** [comment]
@lucafabbri365 alcuni filmati sono protetti da DRM, ma le ultime modifiche dovrebbero permettere la riproduzione anche di questi stream. Hai installato l'ultima versione del plugin? Potresti farmi un esempio di qualche video che non funziona, così provo?

**Comment by M4tT3d** [comment]
Ciao. È successo anche a me oggi. Dice che l'elemento selezionato non è disponibile, ma se vado sul sito dice che per vederlo devo effettuare l'accesso. Il problema si è verificato su rai storia col programma "1919-1922. Cento anni dopo" ep4

**Comment by maxbambi** [comment]
@M4tT3d aggiorna da qui tramite download file zip alla versione più aggiornata e riprova

**Comment by M4tT3d** [comment]
> @M4tT3d aggiorna da qui tramite download file zip alla versione più aggiornata e riprova

Ora. Uso osmc e il repo non è aggiornato. Come mai?

**Comment by maxbambi** [comment]
> > @M4tT3d aggiorna da qui tramite download file zip alla versione più aggiornata e riprova
> 
> Ora funziona. Uso osmc e il repo non è aggiornato. Come mai?

Non è stato più aggiornato il repo ufficiale di kodi per mancanza mia di tempo di preparare l'aggiornamento.
In particolare c'è da risolvere la compatibilità con kodi 19 e python 3

**Comment by awambawamb** [comment]
l'altro ieri sono riuscito a vedere Rush dalla sezione Film e una puntata di Milleluci dalle Teche Rai, mentre oggi funzionano solo le dirette. Ho installato Kodi due settimane fa come componente aggiuntivo di Retropie, installato ex novo a inizio Gennaio.

**Comment by maxbambi** [comment]
> l'altro ieri sono riuscito a vedere Rush dalla sezione Film e una puntata di Milleluci dalle Teche Rai, mentre oggi funzionano solo le dirette. Ho installato Kodi due settimane fa come componente aggiuntivo di Retropie, installato ex novo a inizio Gennaio.

@awambawamb ho provato ad utilizzare il plugin e non ho rilevato anomalie. Se non lo hai fatto, aggiorna il plugin utilizzando il file zip all'indirizzo https://github.com/maxbambi/plugin.video.raitv/archive/master.zip

**Comment by federicodisante** [comment]
Ciao @maxbambi.

Volevo segnalare che effettivamente la congettura di @lucafabbri365, ovvero che alcuni contenuti diventino accessibili solo dopo essersi autenticati, potrebbe essere corretta.

Ho dedicato un paio di ore a comprendere come mai alcuni episodi de "Le avventure di Paddington" (un cartone che mio figlio adora!!!) non fossero disponibili nell'addon, confrontando il traffico di rete sul PC (dove ero autenticato e potevo vedere in particolare l'episodio 23) ed il traffico su una installazione Raspeberry con libreelec (9.2.6) con kodi 18.9 e plugin 3.5.1, installato dal repository ufficiale.

Dopo aver analizzato un poco di traffico, mi è rivenuto in mente che avevo letto questo thread ed ho provato a vedere cosa succedeva senza autenticazione: sono proposti gli stessi del plugin (in particolare manca il mitico episodio 23 sigh ! ;). Ciò vuol dire che senza autenticazione non vengono proposti tutti i contenuti (spero di non aver fatto la figura del commissario Auricchio in Fracchia la belva umana! ;)))

Spero di essere stato di aiuto.
Federico

**Comment by maxbambi** [comment]
@federicodisante 
Sinceramente non so cosa risponderti...
Sono andato ad effettuare la ricerca per le avventure di Paddington... risultato del plugin: 16 episodi, quelli da 1 a 15 e poi il 26
Poi sono andato sul sito raiplay.it, mi sono collegato con il mio account e .... 16 episodi ... gli stessi
Dunque nel mio test non sono uscite fuori differenze fra plugin e sito... cosa può essere successo? BOH!!

Certo questo cartone deve costare tanto!!! Tutte le puntate hanno una durata dei diritti brevissima!

**Comment by federicodisante** [comment]
> @federicodisante
> Sinceramente non so cosa risponderti...
> Sono andato ad effettuare la ricerca per le avventure di Paddington... risultato del plugin: 16 episodi, quelli da 1 a 15 e poi il 26
> Poi sono andato sul sito raiplay.it, mi sono collegato con il mio account e .... 16 episodi ... gli stessi

Invece oggi sono disponibili sempre 16 episodi, quelli da 8 a 22 e poi sempre la 26.
Quindi probabilmente ruotano!

> Dunque nel mio test non sono uscite fuori differenze fra plugin e sito... cosa può essere successo? BOH!!

Non saprei, fatto sta che ricordo perfettamente di aver visto più puntate avendo fatto la login (sempre che non abbia avuto allucinazioni! ;)

> Una cosa che si può riscontrare è che anche le puntate mancanti sono disponibili nei server e possono essere trovare
> tramite una ricerca google...

Si, vero!

> 
> Certo questo cartone deve costare tanto!!! Tutte le puntate hanno una durata dei diritti brevissima!

Approfitto per ringraziarti per il tempo che dedichi al plugin.
Federico
