### ISSUE TITLE
CCurlFile::FillBuffer - Failed: SSL connect error(35)

### ISSUE THREAD

**Issue by andrea99boban** [maxbambi/plugin.video.raitv#30]
Non mi funziona il live streaming su vari linux. Su android va. 

Su linux il log dice: CCurlFile::FillBuffer - Failed: SSL connect error(35)

versioni python:
Python 2.7.18 (default, Aug  4 2020, 11:16:42)
Python 3.8.5 (default, Jul 28 2020, 12:59:40)

**Comment by maxbambi** [comment]
@andrea99boban, effettivamente ci sono dei problemi con il live stream, ma non ho capito bene come risolverli...
la cosa curiosa è che ho tre kodi installati su tre pc con ubuntu diversi: su due lo streaming funziona e su uno no...

il punto critico è questo if (originale di  @nightflyer73)
```
    # Handle RAI relinker
    if url[:53] == "http://mediapolis.rai.it/relinker/relinkerServlet.htm" or \
        url[:56] == "http://mediapolisvod.rai.it/relinker/relinkerServlet.htm" or \
        url[:58] == "http://mediapolisevent.rai.it/relinker/relinkerServlet.htm":
        xbmc.log("Relinker URL: " + url)
        relinker = Relinker()
        params = relinker.getURL(url)
        url = params.get('url','')
        ct = params.get('ct','')
        key = params.get('key','')
```
La condizione viene verificata solo se l'indirizzo contiene "http" invece di "https" e dunque nel primo caso si utilizza la classe Relinker e si determina l'indirizzo diretto per lo streaming.
Nel secondo caso kodi avvia la riproduzione dell'indirizzo del relinker e quindi senza conoscere quello diretto e dunque a volte  fa, a volte no...
Quella che è la cosa stupida è che non ho capito perché ottengo degli errori se aggiungo nell'if anche gli "https"

**Comment by fsp22** [comment]
ma non si potrebbe convertire la condizione dell'if in una regex?
Così si semplifica il codice e si gestiscono facilmente più casi 


    for url in ("http://mediapolis.rai.it/relinker/relinkerServlet.htm",
            "http://mediapolisvod.rai.it/relinker/relinkerServlet.htm",
            "http://mediapolisevent.rai.it/relinker/relinkerServlet.htm",
            "https://mediapolis.rai.it/relinker/relinkerServlet.htm",
            "https://mediapolisvod.rai.it/relinker/relinkerServlet.htm",
            "https://mediapolisevent.rai.it/relinker/relinkerServlet.htm",
            "https://ERRATO.rai.it/relinker/relinkerServlet.htm"):

        res = re.match(r'https?://mediapolis.*\.rai.it/relinker/relinkerServlet.htm.*', url)

        print(url, True if res else False)

**Comment by maxbambi** [comment]
@fsp22, certo che si può fare... il problema non è quello, bensì che con gli indirizzi "https" la funzione nella classe relinker fornisce un errore

**Comment by andrea99boban** [comment]
ho letto che kodi su linux usa il python di sistema, mentre su altri os usa un suo python interno...non puo' essere che curl funzioni diversamente nei due casi ? Ovunque (ubuntu, raspbian) ho python aggiornato, non va...su android invece va. Potrei provare su win10 domani...

**Comment by andrea99boban** [comment]
E su Win10 infatti funziona - allora c'e' quacosa di "troppo avanzato" nel python di sistema su Linux ...

**Comment by maxbambi** [comment]
@andrea99boban, nell'ultima versione ho attuato un "vergognoso" stratagemma, cioè quello di convertire l'url da https a http...
adesso sembra funzionare anche nel pc ubuntu 18.04 in cui precedentemente non funzionava lo stream.

Prova a vedere se ti funziona

**Comment by andrea99boban** [comment]
Funziona alla grandissima! Grazie e buon weekend!
