### ISSUE TITLE
impossibile riprodurre con Kodi su Firestick 2gen

### ISSUE THREAD

**Issue by flapane** [maxbambi/plugin.video.raitv#36]
Salve,

Qualsiasi canale nel plugin provi a riprodurre (live o VOD), appare un popup che dice che non è possibile riprodurre i contenuti, assieme ad un http403 (leggi ancora per i dettagli). Nel log appare un errore col demux.

Questo problema non si verifica col plugin di Mediaset.

Nota: in Kodi ho abilitato un proxy HTML che punta ad un altro indirizzo nella mia LAN. La mia sensazione (validata dal log del proxy) è che il tuo plugin non tenga conto del proxy durante la riproduzione, altrimenti non verrebbe prodotto un http403. Infatti il plugin di Mediaset funziona alla perfezione, perché si "accorge" del proxy durante la riproduzione.
Stranamente, mentre carica le anteprime e la lista dei canali, il tuo plugin usa correttamente il proxy impostato in Kodi. Il problema appare solo durante la riproduzione.

Ho caricato il log su https://paste.kodi.tv/qoxojeleqi

Grazie in anticipo!

**Comment by maxbambi** [comment]
@flapane, alcune parti del plugin sono ancora quelle originali di @nightflyer73 e quindi non le conosco in dettaglio, comunque provo a capirci qualcosa.
Da quello che vedo nel log, il plugin riesce a raggiungere il link del relinker
`Relinker URL: http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803`
e a determinare il link diretto allo streaming
`Media URL: https://raiuno1-live.akamaized.net/hls/live/598308/raiuno1/raiuno1/playlist_ma.m3u8?hdnea=st=1619269402~exp=1619269552~acl=/*~hmac=2ccd26471f46f001adcf6a5f80cfffa47d448361a13cac39a3b22953e215e6b5`
A questo punto viene cambiata la proprietà dell'oggetto nella lista, aggiungendogli il link che viene avviato al click 
`item=xbmcgui.ListItem(path=url + '|User-Agent=' + urllib.quote_plus(Relinker.UserAgent))`
`xbmcplugin.setResolvedUrl(handle=handle, succeeded=True, listitem=item)`
Probabilmente si potrebbero adesso togliere molti di questi comandi e inserire in input solo l'url del relinker, lasciando
tutto in automatico: la cosa serviva per poter selezionare sempre la qualità migliore.

Ho guardato anche il codice del plugin di mediaset, ma non vedo sostanziali differenze

Il fatto che non venga considerato il proxy non mi convince perché l'errore è 403 (cioè forbidden) e non 404 (cioè not found).
Qual è il motivo dell'uso del proxy?

**Comment by flapane** [comment]
Salve Max,

Il Proxy non viene considerato perché analizzando il traffico che vi passa è esattamente 0 bytes (il Proxy è sul telefono), mentre con Mediaset, oppure aprendo il tuo Plugin per vedere la lista canali o l'elenco dei programmi nella mediateca, passa tutto correttamente da lì. A naso, il problema risiede nel come il proxy in Kodi (v18 e v19, su Firestick) interagisce col tuo plugin in fase di riproduzione video. È come se venisse completamente bypassato in quel caso.
Intanto grazie per la risposta ed eventuale aiuto.
