### ISSUE TITLE
Exception in VOD Search

### ISSUE THREAD

**Issue by DrSchottky** [maxbambi/plugin.video.raitv#37]
Hi,
when I try to search for a VOD content I get a genereic error popup and this exception on the log
```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
		- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
	   Error Type: <class 'KeyError'>
	   Error Contents: 'landscape'
	   Traceback (most recent call last):
		 File "/mnt/internal_sd/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.raitv/default.py", line 818, in <module>
		   search_ondemand_programmes()
		 File "/mnt/internal_sd/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.raitv/default.py", line 646, in search_ondemand_programmes
		   liStyle.setArt({"thumb": raiplay.getThumbnailUrl(item["images"]["landscape"])})
	   KeyError: 'landscape'
	   -->End of Python script error report<--
```
I'm running version 3.6.1 of the plugin on Kodi 19.1 for Android

**Comment by maxbambi** [comment]
@DrSchottky, 
this problem can be solved adding a control before the command, but do you remember the search you made?
It could be useful to obtain this error again...

**Comment by DrSchottky** [comment]
Yep, It happens only with some keywords, like "il" or "io"
I think I found the problem: these entries of `programmiAZ-elenco.json` don't have the expected "landscape" attribute

`
{'tipology': '', 'inOnda': False, 'status': 'READY', 'name': 'Giuseppe Fiorello', 'PathID': 'http://www.rai.it/raiplay/collezioni/giuseppefiorello/?json', 'ID': 'ContentItem-6f52c3e9-759d-4c0a-8fa2-64f6282fcdf9', 'images': {'portrait43': '/dl/img/2019/02/18/1550505909199_1536x2048.jpg', 'landscape43': '/dl/img/2019/02/18/1550505909199_2048x1536.jpg', 'square': '/dl/img/2019/02/18/1550505909198_2048x2048.jpg', 'portrait': '/dl/img/2019/02/18/1550505909198_1152x2048.jpg'}, 'type': 'Raiplay configuratore programma raccolta Item'}
`

`
{'tipology': '', 'inOnda': False, 'status': 'READY', 'name': 'Barocco italiano', 'PathID': 'http://www.rai.it/raiplay/collezioni/baroccoitaliano/?json', 'ID': 'ContentItem-2cea5a5c-b328-463a-bcbe-fcae06cf681d', 'images': {'portrait43': '/dl/img/2020/04/23/1587671081043_1536x2048.jpg', 'landscape43': '/dl/img/2020/04/23/1587671081043_2048x1152.jpg', 'square': '/dl/img/2020/04/23/1587671081043_2048x2048.jpg'}, 'type': 'Raiplay configuratore programma raccolta Item'}
` 

`
{'tipology': '', 'inOnda': False, 'PLRanno': ' ', 'status': 'READY', 'name': "Meraviglie d'Italia", 'PathID': 'http://www.rai.it/raiplay/collezioni/meraviglieditalia/?json', 'ID': 'ContentItem-64aaa57b-4cf9-4f34-a1bd-0cd01a2497f7', 'images': {'portrait43': '/dl/img/2018/05/18/1526636375126_meraviglie%20ditalia%201536x2048.jpg', 'landscape43': '/dl/img/2018/05/18/1526636375126_meraviglie%20ditalia%202048x1536.jpg', 'square': '/dl/img/2018/05/18/1526636375125_meraviglie%20ditalia%202048x2048.jpg', 'portrait': '/dl/img/2018/05/18/1526636375125_meraviglie%20ditalia%201152x2048.jpg'}, 'type': 'Raiplay configuratore programma raccolta Item'}`

**Comment by maxbambi** [comment]
@DrSchottky, retry after last commit.

**Comment by DrSchottky** [comment]
Now it works fine.
Grazie! 🙂
