### ISSUE TITLE
crash Kodi se pagine recenti!

### ISSUE THREAD

**Issue by Olivastro12** [maxbambi/plugin.video.raitv#39]
Buongiorno,
uso l'addon su Raspberry Pi 4 2gbRam usando LibreElec.
Pensavo andasse tutto bene dopo esser riuscito a vedere finalmente una serie TV rai che avevo perso.
Tuttavia, provando a vedere gli eventi sportivi in aggiornamento continuo, questi video (tutti!) mandano in crash Kodi o non partono proprio 
In particolare basket serie A ed Europei di calcio.

Non c'è modo di usare Raiplay registrando il proprio account Raiplay che sul PC avevo attivato?

grazie!

**Comment by maxbambi** [comment]
@Olivastro12, scusami perché non ti ho risposto prima, ma non capisco perché non mi arrivano più le notifiche al mio indirizzo di posta.
Per riprodurre l'errore potresti rispondere? 
Com'è che raggiungi questi video sportivi, tramite l'archivio RaiSport? tramite replay?  oppure da programmi on demand?

**Comment by Olivastro12** [comment]
Grazie per aver visto e risposto anzitutto!
Quello dei video sportivi era solo un esempio tra altri
Provo a darti dettaglio di quel che NON parte se entro da (non l'elenco di TUTTI i video che non partono, ci metterei tantissimo, ma, come credo tu mi stia chiedendo, del "comportamento" dell'addon rispetto ad alcuni video. Due esempi di ingressi con video falliti:1. Archivio Rai Sport. Non vanno i video di Pallacanestro (ne ho provati alcuni) e di Calcio/Serie A2. Home. /Sport. Non vanno le puntate di "Europei a casa The Jackal" e in /Documentari il primo video ad es.
Il comportamento in tutti questi casi è "icona di attesa rotante" per 20/30 secondi e poi msg che dice "Riproduzione Fallita" (con la versione 18 ultima stabile addirittura si impallava e dovevo spegnere e riaccendere il sistema. Ora con la 19 almeno... attendo il msg e proseguo)

E qui se anche solo mi dai un link di come si fa a leggere i log che dovrei per esserti d'aiuto... NON SONO RIUSCITO a trovare da nessuna parte una spiegazione di come posso leggere questi file di testo immagino che riportano gli errori che immagino per te sarebbero oro in questo caso.
Grazie intanto!
p.s. superfluo dire che il tutto gira su raspberry pi 4 2Gb ram?

    Il lunedì 28 giugno 2021, 08:12:17 CEST, Max ***@***.***> ha scritto:  
 
 


@Olivastro12, scusami perché non ti ho risposto prima, ma non capisco perché non mi arrivano più le notifiche al mio indirizzo di posta.
Per riprodurre l'errore potresti rispondere?
Com'è che raggiungi questi video sportivi, tramite l'archivio RaiSport? tramite replay? oppure da programmi on demand?

**Comment by maxbambi** [comment]
@Olivastro12 
Ti rispondo con alcune informazioni e vediamo quello che è possibile aggiustare.
Premetto che utilizzo kodi su pc (principalmente ubuntu, ma anche windows lo posso testare) e quindi non possibilità di provare altri dispositivi. Il plugin è costruito per simulare un browser di pc e quindi controlla sempre che quello che non ti funziona nel plugin sia funzionante su un browser 
> Grazie per aver visto e risposto anzitutto! Quello dei video sportivi era solo un esempio tra altri 
> Provo a darti dettaglio di quel che NON parte se entro da (non l'elenco di TUTTI i video che non partono, ci metterei tantissimo, ma, come credo tu mi stia chiedendo, del "comportamento" dell'addon rispetto ad alcuni video. 

> Due esempi di ingressi con video falliti:1. Archivio Rai Sport. Non vanno i video di Pallacanestro (ne ho provati alcuni) e di Calcio/Serie A2. Home. /Sport. 

L'archivio di Raisport è un qualcosa che ho creato leggendo l'html. Non funziona come il resto del plugin che invece legge le informazioni in formato JSON interrogando un apposito database. Basta che ci sia una qualche modifica nel formato di una particolare pagina e il menu risulta vuoto oppure escono fuori degli errori.

 >Non vanno le puntate di "Europei a casa The Jackal" e in /Documentari il primo video ad es. Il comportamento in tutti questi casi è "icona di attesa rotante" per 20/30 secondi e poi msg che dice "Riproduzione Fallita" (con la versione 18 ultima stabile addirittura si impallava e dovevo spegnere e riaccendere il sistema. Ora con la 19 almeno... attendo il msg e proseguo) E qui se anche solo mi dai un link di come si fa a leggere i log che dovrei per esserti d'aiuto... NON SONO RIUSCITO a trovare da nessuna parte una spiegazione di come posso leggere questi file di testo immagino che riportano gli errori che immagino per te sarebbero oro in questo caso. Grazie intanto! p.s. superfluo dire che il tutto gira su raspberry pi 4 2Gb ram? 

Per quanto riguarda il resto la creazione del log avviene selezionando l'opzione log di debug nel menu impostazioni di sistema di kodi. Un log meno verboso viene comunque creato ad ogni crash, ma selezionando l'opzione che ti ho detto ti appare anche a video il percorso del file log e quindi è tutto più facile...
Nel mio caso il percorso è "[cartella user di kodi]/temp/kodi.log"
Alcuni stream di raiplay sono protetti da DRM e quindi si possono riprodurre solo con widevine installato.
Per pigrizia non ho inserito nel plugin la procedura per installarlo: puoi usare inputstreamhelper oppure utilizzare il plugin mediasetplay dove invece hanno inserito un'apposita sezione in "configura"

**Comment by maxbambi** [comment]
@Olivastro12 
aggiornamento: ho provato a vedere se funzionavano le puntate di "Europei a casa The Jackal"...
ieri pomeriggio ho provato la prima completa "Italia-Turchia" e non funzionava (mi dava dei problemi sul leggere dall'url della licence-key) . 

Stamani ho ricontrollato e ho visto che è cambiato il nome del server (boh?) e tutto funziona.
Per farlo funzionare devi aver installato inputstreamhelper e da lì widevine DRM

**Comment by Olivastro12** [comment]
Grazie Max!Avevo già installatoinputstreamhelper e widevine DRMper via di Netflix e Amazon Prime.In effetti ieri sera, entrando da Home, qualcosa di "Europei a casa The Jackal" si vede, o meglio... si vede "il meglio di". 

Ho letto anche la tua precedente e mi ci ritrovo, dunque spero che le trasmissioni che mi interessano (in fondo "Europei a casa The Jackal"... era solo il primo che ho trovato che ho usato come test, ma non è che mi interessi...) potrò sempre vederle.
Ma... non è che si può ottenere l'ingresso al canale "da registrati"? 
Sono arrivato a Kodi perché eravamo stufi di metterci attorno al video del PC quando volevamo guardare Raiplay! Però l'account per entrarci da pc io l'ho! 
Non so una quasi cippa di programmazione, ma oso chiederti se non si può fare in modo che l'addon sia "come entrare da pc nel sito raiplay, con le proprie credenziali, così da vedere tutto"...A differenza di altri provider rai è gratis: paghiamo pure il canone, perché non fare anche l'addon con account?
(la domanda è talmente logica che già mi aspetto un "non è così semplice" o "non si può e basta", ma perché non fartela?:-)

    Il sabato 3 luglio 2021, 10:33:53 CEST, Max ***@***.***> ha scritto:  
 
 


@Olivastro12
aggiornamento: ho provato a vedere se funzionavano le puntate di "Europei a casa The Jackal"...
ieri pomeriggio ho provato la prima completa "Italia-Turchia" e non funzionava (mi dava dei problemi sul leggere dall'url della licence-key) .

Stamani ho ricontrollato e ho visto che è cambiato il nome del server (boh?) e tutto funziona.
Per farlo funzionare devi aver installato inputstreamhelper e da lì widevine DRM
