### ISSUE TITLE
Show All not working

### ISSUE THREAD

**Issue by michele-grifa** [maxbambi/plugin.video.raitv#52]
The option **Show All** in the section Home Page > Film > Show All is not working
The same happen in Home Page > Esplora Per > Film

L'opzione Vedi Tutti, nella sezione Home Page > Film > Vedi Tutti non è funzionante.
Lo stesso avviene in Home Page > Esplora Per > Film

**Comment by maxbambi** [comment]
@michele-grifa prova a vedere se l'albero funziona tutto con le ultime modifiche (versione 3.8.2)
