### ISSUE TITLE
Problems in the on demand section

### ISSUE THREAD

**Issue by numbernumero** [maxbambi/plugin.video.raitv#59]
Hi, first of all a million thanks for this fantastic addon.
 Unfortunately many video on demand does not work such as "World Cup" while with the official android app they all work. 
Maybe it's a login problem???

**Comment by maxbambi** [comment]
@numbernumero  It isn't a login problem...
I can't set kodi to stream videos when they are protected with keys provided by this or similar urls 
https://rai6nb5f.anycast.nagra.com/RAI6NB5F/wvls/contentlicenseservice/v1/licenses?Authorization=eyJ0eXAiOiJKV1QiLC...

I was able to set the plugin with drm protection of different origin, but in this case i can't.
I don't know expert settings of inputstream adaptive to copy what I can read in Chrome developer tools.
I need help...

**Comment by numbernumero** [comment]
I know that this developer (link below) has helped many other developers from other Addons in Kodi.  I wonder if he could be of assistance to you even in this situation.  Perhaps you can contact him.
 This is his contact: https://it.linkedin.com/in/emanuele-guzzetti-b2b922153?original_referer=https%3A%2F%2Fwww.google.com%2F

**Comment by maxbambi** [comment]
> I know that this developer (link below) has helped many other developers from other Addons in Kodi. I wonder if he could be of assistance to you even in this situation. Perhaps you can contact him. This is his contact: https://it.linkedin.com/in/emanuele-guzzetti-b2b922153?original_referer=https%3A%2F%2Fwww.google.com%2F

Ok. His nickname is @phate89

**Comment by numbernumero** [comment]
Any news?
