### ISSUE TITLE
Audio ma non Video

### ISSUE THREAD

**Issue by denics** [maxbambi/plugin.video.raitv#61]
Innanzitutto grazie per questo plugin, I miei bambini guardano moltissimo RaiYoYo e noi guardiamo i telegiornali con il VPN dall'estero.
C'é un problema però molto ricorrente, ho provato tante soluzioni ma non riesco a risolverlo. Molto ma molto spesso, il flusso video si blocca con questo errore:

`2023-02-11 12:40:25.706 T:2056    ERROR <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)`

ripetuto migliaia di volte. Si sente il suono, ma il video rimane congelato.
Qualche consiglio? Utilizzo LibreElec su un Raspberry PI 4 2Gb ram con un hifiberry amp 2 e un televisore 4K connesso via HDMI. Il VPN é la version di protocollo OpenVPN UTP di ProtonVPN - ovviamente Italia.

**Comment by maxbambi** [comment]
@denics Ci sono novità su questo errore?

**Comment by denics** [comment]
Appena testato con la tua ultima versione e no, non ho più visto l'errore. Grazie!
