### ISSUE TITLE
voce fiction non funziona piu'

### ISSUE THREAD

**Issue by red5454** [maxbambi/plugin.video.raitv#62]
grazie per l'ottimo lavoro!
purtroppo devo segnalare che la voce fiction porta solo ai tre puntini.
Percio' e' impossibile vedere le ultime puntate delle fiction perche' non appaiono piu' nemmeno tramite la ricerca generica.
Spero ci sia un rimedio..grazie

**Comment by maxbambi** [comment]
@red5454 la funzione cerca sembra funzionare come sempre: non so che titolo stai cercando...
Confermo però il tuo problema del menu Fiction. Appena ho un po' tempo cerco di vedere cosa è cambiato

**Comment by red5454** [comment]
ottimo grazie e complimenti per la velocita'!!
ti segnalo anche che il menu' "prima pagina" da' errore.
grazie ancora a nome di tutti

**Comment by maxbambi** [comment]
@red5454 ho provato a fare delle ulteriori piccole modifiche alle voci dei menu... 
prova a vedere quello che funziona

**Comment by Lanternius74** [comment]
Ciao e grazie per l'ottimo lavoro svolto, aggiornerai a presto anche la versione per KODI18 del plugin per il problema del cambio delle voci del menù così come hai già fatto con la versione 3.9.1 di matrix?

**Comment by maxbambi** [comment]
@Lanternius74 Vedrò di farlo quando ho un po' di tempo, ma attualmente non ho più un kodi 18 installato su cui provare...

**Comment by maxbambi** [comment]
@Lanternius74 Adesso ho provato ad inserire le nuove modifiche anche in kodi 18, ma non ho controllato se tutto è integrato correttamente

**Comment by Lanternius74** [comment]
> @Lanternius74 Adesso ho provato ad inserire le nuove modifiche anche in kodi 18, ma non ho controllato se tutto è integrato correttamente

Ciao e grazie per la velocità di intervento, ho provato la versione per kodi18 e sembra funzionare tutto, nei prossimi giorni controllerò meglio le varie voci e se trovo dei problemi te lo comunico qui. Grazie ancora.
