### ISSUE TITLE
Archivio Rai Sport

### ISSUE THREAD

**Issue by italfire** [maxbambi/plugin.video.raitv#63]
Ciao, 'Archivio Rai Sport',   'Videonotizie' ,  ' Archivio telegiornali (TG1, TG2 e TG3) ',  'Replay Radio'  e  'In Diretta'  (presente nella sezione Home Page),  i video non funzionano. Provato su firestick "matrix".
Spero in una soluzione sopratutto per 'Archivio Rai Sport' .
Grazie infinite per il lavoro che dedichi a questo addon

**Comment by maxbambi** [comment]
Ciò è dovuto al cambiamento che è stato effettuato nei siti relativi quando tutto è stato unificato in Rai News.
Cercherò di riprogettare tutto in base alla nuova struttura del sito
