### ISSUE TITLE
Sottotitoli non visibili

### ISSUE THREAD

**Issue by andyfav1968** [maxbambi/plugin.video.raitv#64]
Ciao,
ho un caro amico non udente che non riesce a visualizzare i sottotitoli di alcune fiction, per esempio la stagione 3 di "La porta rossa" oppure "Fiori sopra l'inferno".
Grazie di tutto il lavoro che hai fatto.
Ciao

**Comment by andyfav1968** [comment]
Ciao,
non so se può essere utile alla tua verifica.
Ho dato un occhiata a parecchi file json ed ho notato una casistica.
Tutti i sottotitoli che non funzionano hanno uno spazio nel file name, esempio 
Porta Rossa (stagione 3)
	"/dl/video/stl/La_porta_rossa_3_Puntata 5_del_25_01_2023i.srt"
	"/dl/video/stl/La_porta_rossa_Puntata 3_del_18_01_2023i.srt"
	"/dl/video/stl/La_porta_rossa_3_Puntata 7_del_01_02_2023i.srt"
Fiori sopra l'inferno 
	"/dl/video/stl/Fiori_sopra_linferno_Puntata 2_del_13_02_2023i.srt"

La Porta Rossa (Stagione 1 del 2017) i sottotitoli sono quasi tutti visibili , ed infatti non ci sono spazi nel filename.
"/dl/video/stl/Laportarossa_1_.srt"
"/dl/video/stl/Laportarossa6.srt"
Le uniche 2 puntate della stagione 1 che non hanno i sub visibili hanno lo spazio nel filename.

**Comment by maxbambi** [comment]
> Ciao, non so se può essere utile alla tua verifica. Ho dato un occhiata a parecchi file json ed ho notato una casistica. Tutti i sottotitoli che non funzionano hanno uno spazio nel file name, esempio Porta Rossa (stagione 3) "/dl/video/stl/La_porta_rossa_3_Puntata 5_del_25_01_2023i.srt" "/dl/video/stl/La_porta_rossa_Puntata 3_del_18_01_2023i.srt" "/dl/video/stl/La_porta_rossa_3_Puntata 7_del_01_02_2023i.srt" Fiori sopra l'inferno "/dl/video/stl/Fiori_sopra_linferno_Puntata 2_del_13_02_2023i.srt"
> 
> La Porta Rossa (Stagione 1 del 2017) i sottotitoli sono quasi tutti visibili , ed infatti non ci sono spazi nel filename. "/dl/video/stl/Laportarossa_1_.srt" "/dl/video/stl/Laportarossa6.srt" Le uniche 2 puntate della stagione 1 che non hanno i sub visibili hanno lo spazio nel filename.

Il tuo aiuto è stato preziosissimo! Spero di aver risolto questa storia degli spazi codificando in maniera opportuna gli indirizzi...
ora sembra funzionare

**Comment by andyfav1968** [comment]
Ciao max, ho potuto provare solo ora.
Tutto perfetto! Grande.
Grazie da parte mia e dal mio amico non udente.
