### ISSUE TITLE
La funzione cerca in "On Demand TV Shows" non trova voci che si trovano sfogliando

### ISSUE THREAD

**Issue by strk** [maxbambi/plugin.video.raitv#67]
Esempio: se cerco "rocco" i risultati includono "Pimpa e l'anatroccolo Ali'" ma non "Rocco Schiavone"

Questo avviene oggi con lo .zip installato dalla master corrente

PS: grazie infinite per condividere questo codice
PS2: potrebbe essere utile clonare il repository direttamente sotto la directory addons/ ma quando ho provato Kodi si e' rifiutato di leggere l'addon, considerandolo incompatibile, c'e' un modo ?

**Comment by maxbambi** [comment]
@strk Prova l'ultima versione per vedere se funziona la nuova ricerca

**Comment by strk** [comment]
Grazie, funziona :)
