### ISSUE TITLE
Errore Python

### ISSUE THREAD

**Issue by Gythion** [maxbambi/plugin.video.raitv#7]
Ciao, ho questo errore qua: https://is.gd/IjzL84. Il video è: La Grande Storia - Falcone contro Riina. L'ho notato pure su Chi l'ha visto.

**Comment by maxbambi** [comment]
@Gythion, ho controllato il video che mi hai segnalato e l'errore dipende dalla struttura non corretta del file json all'indirizzo
https://www.raiplay.it/video/2019/05/La-Grande-Storia-Anniversari-Falcone-contro-Riina-la-guerra-di-Cosa-Nostra-1047d1db-67dc-488b-977e-8cc8fae91a69.html?json

Il titolo della pagina è 
La Grande Storia "Anniversari" - Falcone contro Riina: la guerra di Cosa Nostra
e le virgolette nel titolo causano l'errore di sintassi che hai inviato
```
Error Contents: Expecting , delimiter: line 1 column 5107 (char 5106) 
```
perché la prima occorrenza di ", termina in anticipo la stringa causando l'errore...
Purtroppo quelle virgolette sono lo stesso carattere " usato per le stringhe nel formato json
e quindi indistinguibili da quelle giuste.

**Comment by maxbambi** [comment]
Ho fatto una piccola modifica al codice per ovviare a questo inconveniente...
prova se ora funziona

**Comment by Gythion** [comment]
"Perfietto"
