### ISSUE TITLE
Some channels stop streaming after a fixed amount of time

### ISSUE THREAD

**Issue by SimoPk** [maxbambi/plugin.video.raitv#73]
Rai1 stops streaming exactly after 2:10, Rai2 stops after 2:50 (don't remember the exact time point) and so on. I noticed that only channels that stream from akamai servers have this issue (eg: Rai3 works fine).

After long testing, I was able to solve this issue by using inputstream.adaptive also for hls streams like these ones, by patching default.py like this:

![immagine](https://github.com/maxbambi/plugin.video.raitv/assets/11347123/602db550-996b-4ed0-a507-f1a9148045ff)

do you think it's a reasonable modification?

thanks for your precious work

**Comment by maxbambi** [comment]
@SimoPk I change the code (matrix version). Try  to download new version of plugin and test if it is all ok.
Thank you for your help!!!

**Comment by SimoPk** [comment]
tested it with Rai1 and it seems to work, it streamed without interruptions with a couple of hours (Kodi 20.3, vanilla under Windows and Libreelec on odroid c2)
