### ISSUE TITLE
È in arrivo un nuovo e sostanzioso aggiornamento di RaiPlay

### ISSUE THREAD

**Issue by nx-99** [maxbambi/plugin.video.raitv#8]
Ciao, se non l'avessi già letto in giro, ti informo che è in arrivo un grosso aggiornamento di RaiPlay. Dal 30 ottobre, infatti, l’intero sito web e le applicazioni di Raiplay verranno aggiornate con contenuti esclusivi e un’interfaccia grafica completamente nuova.

https://www.dday.it/redazione/32745/raiplay-gioca-a-fare-netflix-nuova-grafica-e-piu-contenuti-dedicati

**Comment by maxbambi** [comment]
@nx-99 , immaginavo che sarebbe cambiato qualcosa in occasione dell'arrivo di Fiorello su Raiplay. La veste grafica ci interessa il giusto, l'importante è che l'archivio rimanga accessibile attraverso il formato json come avviene adesso....  staremo a vedere, grazie per la segnalazione
