### ISSUE TITLE
Live TV / Rai 1 always fails to play

### ISSUE THREAD

**Issue by emanuele** [maxbambi/plugin.video.raitv#80]
Great kodi add-on! Thanks for your work.

The only thing that consistently does not work on kodi 19.4.0 (Raspbian OS 32bit, kodi official package, on Raspberry Pi 4) is Live TV for Rai 1. When clicking on it I get:
```
Playback failed
One or more items failed to play. Check the logs for more information about this message.
```
All other Rai channels work. Replay TV works for all Rai channels, Rai 1 included.

The version of Rai Play add on installed from Kodi add-on repository is 4.1.2.

**Comment by maxbambi** [comment]
@emanuele same issue #79.
I'm working to solve this problem.
I think there are problems when you try to stream abroad from Italy, even if with a VPN
